<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE saad [
    <!ELEMENT saad (hasnain*)>
    <!ELEMENT hasnain (name+,email?,age*,city)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT city (#PCDATA)>

    <!ENTITY a "ASAD">

    <!ATTLIST hasnain id CDATA #REQUIRED>
    ]>
<saad>

    <hasnain id="">
        <name>&a;</name>
        <email>Saad@gmail.com</email>
        <age>18</age>
        <city>karachi</city>
    </hasnain>

    <hasnain id="">
        <name>Saad</name>
        <email>Saad@gmail.com</email>
        <age>18</age>
        <city>karachi</city>
    </hasnain>

    <hasnain id="">
        <name>Saad</name>
        <email>Saad@gmail.com</email>
        <age>18</age>
        <city>karachi</city>
    </hasnain>
</saad>